In [2]:
#creating a numpy array
import numpy as np
myVar = np.array([1,6,8,9,7])
print(myVar)
print(type(myVar))

[1 6 8 9 7]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
arr= np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [5]:
#0-D array
import numpy as np
arr= np.array(34)
print(arr)

34


In [6]:
#1-D array
oneD = np.array([1,2,3,4])
print(oneD)

[1 2 3 4]


In [8]:
#2-D array
twoD = np.array([[1,2,3],[11,23,45]])
print(twoD)

[[ 1  2  3]
 [11 23 45]]


In [9]:
#3-D array
threeD = np.array([[[1,2,3],[4,5,6]],[[11,23,45],[21,34,56]]])
print(threeD)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 23 45]
  [21 34 56]]]


In [11]:
myarr=np.array([12,67,23,45])
print(myarr[2])

23


In [14]:
#accessing array element
myarr=np.array([[12,23,45,67],[23,45,67,89]])
print(myarr[1,2])

67


In [17]:
#accesss the elemnt of the second of the first aray
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [19]:
arr=np.array([1,2,3,4,5,6,7,8,9])

print(arr[3:9:2])

[4 6 8]


In [25]:
#numpy shape
arr=np.array([[1,2,3,4],[4,5,6,7]])
print(arr.shape)

(2, 4)


In [27]:
#joining array
arr1=np.array([34,45,56,77])
arr2=np.array([45,34,56,78])
arr3=np.array([8,7,6])
newarr=np.concatenate((arr1,arr2,arr3))
print(newarr)

[34 45 56 77 45 34 56 78  8  7  6]


In [28]:
#splitting an array
arr=np.array([1,2,3,4,5,6,7,8,9])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [30]:
arr=np.array([45,67,56,34,78,45,67,67])
x=np.where(arr==67)
print(x)

(array([1, 6, 7], dtype=int64),)


In [31]:
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [34]:
#sort numpy
import numpy as np
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [33]:
import numpy as np
arr=np.array(["Banana","Cherry","Apple"])
print(np.sort(arr))

['Apple' 'Banana' 'Cherry']
